#!/usr/bin/env perl
$latex = 'uplatex -synctex=1 -halt-on-error';
$latex_silent = 'uplatex -synctex=1 -halt-on-error -interaction=batchmode';
$bibtex = 'upbibtex';
$dvipdf = 'dvipdfmx %O -o %D %S';
$makeindex = 'mendex %O -o %D %S';
$max_repeat = 5;
$pdf_mode = 3;
$pvc_view_file_via_temporary = 0;
if ($^O eq "linux") {
    $pdf_previewer = "/usr/bin/evince";
} elsif ($^O eq "darwin") {
    $pdf_previewer = "open -ga /Applications/Skim.app";
}
$biber = 'biber --bblencoding=utf8 -u -U --output_safechars';
